version: "3"
services:
    frontend:
        build: ./employee-frontend
        image: my-react-app
        ports:
            - "5173:5173"

    backend:
        build: ./employee-backend
        image: my-spring-boot-app
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/employee_creator
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=
        depends_on:
            - db

    db:
        image: mysql:latest
        environment:
            - MYSQL_DATABASE=employee_creator
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-u", "root"]
            timeout: 20s
            retries: 10
